---
title: "Collaborator Analysis"
format: html
editor: visual
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
lobster_traps <- read_csv("data/Lobster_Trap_Counts_All_Years_20210519.csv")
```

## Convert missing values

```{r}

## Prints unique values in a column (in this case, the region)
unique(lobster_traps$TRAPS)

```

```{r}

# Replacing -99999 with NA in the TRAPS column
lobster_traps_temp <- lobster_traps %>%
  mutate(TRAPS = na_if(TRAPS, -99999))

# Get unique values from the TRAPS column
unique_traps <- unique(lobster_traps_temp$TRAPS)

# If you want to view the unique values
print(unique_traps)
```

## **Question 2**

```{r}
## Prints unique values in a column (in this case, the region)
unique(lobster_traps$SITE)
```

```{r}
#Create and store a subset that does NOT include observations from Naples Reef (NAPL). Check your output data frame to ensure that NAPL is NOT in the data frame
 
lobster_traps_temp_2 <- lobster_traps_temp %>% 
  filter(SITE %in% c("ABUR", "AHND", "AQUE", "CARP", "GOLB", "IVEE", "MOHK", "AHND to AQUE", "AHND TO AQUE"))

## Prints unique values in a column (in this case, the region)
unique(lobster_traps_temp_2$SITE)


```

## Question 3

```{r}
#Create and store a subset with lobsters at Carpinteria Reef (CARP) AND number of commercial trap floats is greater than 20. Check your output.

lobster_traps_temp_3 <- lobster_traps_temp %>% 
  filter(SITE =="CARP", TRAPS >20)
```

## Question 4

```{r}
#Find the maximum number of commercial trap floats using max() and group by SITE and MONTH. Think about how you want to treat the NA values in TRAPS (Hint: check the arguments in max()). Check your output.

unique(lobster_traps$MONTH)
unique(lobster_traps$SITE)
unique(lobster_traps_temp_2$TRAPS)

lobster_traps_temp_4 <- lobster_traps %>%
  group_by(SITE, MONTH)

  
```
