---
title: "Joana Analysis"
format: html
editor: visual
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
lobster_abundance <- read_csv("data/Lobster_Abundance_All_Years_20220829.csv")
```

```{r}
# summarize() practice
summary(lobster_abundance)
```


```{r}
#  Replace -99999 with NA in SIZE_MM column
lobster_abundance <- lobster_abundance %>%
  mutate(SIZE_MM = na_if( SIZE_MM, -99999))
```

```{r}
# remove NAPL
not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")
```

```{r}
# create subset of Lobsters at AQUE and length greater than 70mm 
aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)
```

```{r}
# tracing maximum length and group bby SITE and MONTH
max_lobster <- lobster_abundance %>% 
  group_by(SITE, MONTH) %>% 
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))
```

## Exercise: Data Visualization

```{r}
# creating a multipanel plot of Lobster carapace length
ggplot(lobster_abundance, aes(x = SIZE_MM)) +
  geom_histogram()+
  facet_wrap(~SITE)


```

```{r}
# line graph for the total number of Lobsters observed

lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

ggplot(data = lobsters_summarize, aes(x = YEAR, y= COUNT)) +
  geom_line(aes(color = SITE))
```

```{r}
# amount of small and large sized carapace lobsters at each site

lobster_size_lrg <- lobster_abundance %>%
  filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()
# bar plot
ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
    geom_col()
# dodged bar plot
ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
    geom_col(position = "dodge")+
  theme_dark()

```

